### ISSUE TITLE
Wifi not working sonoma , efi 2.0

### ISSUE THREAD

**Issue by bouyhy1989** [Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh#15]
Thank you so much bro but wifi is not working on my 820 g3 i5 6300u on sonoma with your efi !! If i revert to airporitlwm will it work ? I just used your efi without modifying anything .
Thanks a lot for your help
![IMG_20230927_014316_HDR](https://github.com/Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh/assets/67211127/406102d2-9b55-4d2c-a894-3f20779ade54)
![IMG_20230927_014349_HDR](https://github.com/Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh/assets/67211127/f902b5d1-1550-41ae-b770-07ce3f412480)

**Comment by Lost-Entrepreneur439** [comment]
Itlwm uses a separate app called Heliport to work, it does not use macOS's built in wi-fi stack. You will need to download Heliport. Airportitlwm is currently broken on Sonoma.

**Comment by bouyhy1989** [comment]
Heliport is it a kext or do i have to run in on my sonoma hackintosh?

**Comment by Lost-Entrepreneur439** [comment]
It's an app.

**Comment by bouyhy1989** [comment]
do you have a link plz?

**Comment by bouyhy1989** [comment]
thank you it worked , will airportitlwm be updated for sonoma any soon?

**Comment by Lost-Entrepreneur439** [comment]
I don't know, I'm not the developer of airportitlwm.

**Comment by bouyhy1989** [comment]
Thank you for your help
