### ISSUE TITLE
Sonoma Airportitlwm is available in "beta" (alpha)

### ISSUE THREAD

**Issue by biertester** [Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh#16]
Just so you know, and it works way better than just itlwm and heliport haha! here is the link of the last version: https://github.com/OpenIntelWireless/itlwm/files/12299048/AirportItlwm-Sonoma-Preview05.zip

**Comment by bouyhy1989** [comment]
Already tried it on the stable sonoma but it wont let macos sign in !!

**Comment by biertester** [comment]
Wtf 😭 d*mn, works on my 820 G3..

U sure u tried the latest preview? (Just in case)

Le jeu. 28 sept. 2023 à 11:21, bouyhy1989 ***@***.***> a
écrit :

**Comment by Lost-Entrepreneur439** [comment]
I used the beta for airportitlwm back when this was a Ventura EFI and airportitlwm had no stable release for Ventura, and it was incredibly buggy, and I'm assuming it'll be the same for Sonoma. I will continue using itlwm until airportitlwm gets a stable Sonoma release.
